### ISSUE TITLE
jdbc connector - connection failed, connector reports running

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-database-connectors#249]
Opening up for discussion - we need to consider how to help users understand the state of their environment, as well as to aid github search for anyone else getting a similar issue

In this issue I document a situation where
 - an invalid URL was used (why is the subject of another track!)
 - connector status reports as running
 
 Whilst there is an audit log entry, it's not clear how to check the current connectivity.
 Arguably I wonder if the connector status should be in a 'failed' state rather than 'running'
 
 

I setup a test environment using
 - IBM db2 (cloud)
 - db2 jdbc driver
 - coco pharma lab environment
 - a test notebook
 
 I was not seeing any database metadata in egeria.
 
 Using debug in intelliJ I was able to locate the issue to an invalid database URL:
 
 `jdbc:db2://55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;sslConnection=true;`
 
 This was seen by debugging into DriverManager.java
 here the exception was reported as
 ```
 com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10165][10036][4.32.28] Invalid database URL syntax: jdbc:db2://55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;sslConnection=true;. ERRORCODE=-4461, SQLSTATE=42815
 ```
 
 This was initially set since the 'sslConnection' setting needs to be set to true
 
 This was reported in the log as
 ```
 Tue Nov 29 16:16:12 GMT 2022 intserv Exception JDBC-INTEGRATION-CONNECTOR-0005 Supplementary information: log record id e1fc3190-9ec5-49b7-b731-e7d481dec335 com.ibm.db2.jcc.am.SqlSyntaxErrorException returned message of [jcc][10165][10036][4.32.28] Invalid database URL syntax: jdbc:db2://55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;sslConnection=true;. ERRORCODE=-4461, SQLSTATE=42815 and stacktrace of
com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10165][10036][4.32.28] Invalid database URL syntax: jdbc:db2://55fbc997-9266-4331-afd3-888b05e734c0.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31929/bludb;sslConnection=true;. ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:116)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:426)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:117)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at org.odpi.openmetadata.adapters.connectors.resource.jdbc.JdbcConnector$JdbcConnectorAsDataSource.getConnection(JdbcConnector.java:35)
	at org.odpi.openmetadata.adapters.connectors.integration.jdbc.JdbcIntegrationConnector.connect(JdbcIntegrationConnector.java:69)
	at org.odpi.openmetadata.adapters.connectors.integration.jdbc.JdbcIntegrationConnector.refresh(JdbcIntegrationConnector.java:42)
	at org.odpi.openmetadata.governanceservers.integrationdaemonservices.handlers.IntegrationConnectorHandler.refreshConnector(IntegrationConnectorHandler.java:487)
	at org.odpi.openmetadata.governanceservers.integrationdaemonservices.threads.IntegrationDaemonThread.run(IntegrationDaemonThread.java:96)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

After this the notebook status query for the connector reports
```
One integration service defined for integration daemon intserv
 
Integration Service: Database Integrator OMIS
  Integration Connector Reports: 
      Integration Connector: jdbcresource
         status:                   RUNNING
         lastStatusChange:         2022-11-29T16:05:36.538+00:00
         lastRefreshTime:          2022-11-29T16:17:50.429+00:00
         minMinutesBetweenRefresh: 60
```

Whilst the connector is active/running, it's in a bad way. it's not connected to it's source.

This could be transient, so leaving the connector running to execute the next timed refresh likely makes sense - though even there, one might want to pull that refresh forward (shorter delay)

**Comment by planetf1** [comment]
The scenario here is
* connect attempt to database is blocking for 10 minutes
* this is repeated correctly at the refresh interval
* All the time the status continues to show as 'RUNNING'

**Comment by mandy-chessell** [comment]
`RUNNING` means is that the connector is running and has not reported an error (by throwing an exception) to the integration daemon.  If it throws an exception it moves to `FAILED` state.  Once in `FAILED` state the connector needs to be restarted (REST call available to do that).  It is used for permanent errors that need operator intervention - ie bad config.

It is OK for a connector to stay in `RUNNING` state for temporary issues (such as an outage) that it is handling.  It should log to the audit log to show it is not able to catalog.

There is a grey area on the choice of what is a temporary issue or one that needs operator intervention.

**Comment by mandy-chessell** [comment]
Integration daemon diagnostic guide includes an explanation.  Are there aspects that could be improved?

https://egeria-project.org/guides/diagnostic/integration-daemon-diagnostic-guide/#retrieving-status-of-the-connectors
